# VodoHod
POGRESHOST = 3
TIMER_FOR_S_OBRAT = 15
TIMER_FOR_S_VERTIK = 10
VERTIK_CHANGE_Y = 11
VERTIK_KOEF = 1.4
VERTIK_ANGLE = 90
VVERH_CHANGE_Y = VERTIK_CHANGE_Y * 1.25
VVERH_KOEF = 0.5
VVERH_ANGLE = 45
VVERH_RAZNICA = 30
FALL_CHANGE = -9
SUMMA_RAZNICA = 10
FIRST_GRANICA_Y_EJECTION = 10
SECOND_GRANICA_Y_EJECTION = 20
THIRD_GRANICA_Y_EJECTION = 50
FIRST_CHANGE_Y_EJECTION = 0.1
SECOND_CHANGE_Y_EJECTION = 1
THIRD_CHANGE_Y_EJECTION = 3
ELSE_CHANGE_Y_EJECTION = 5
CHANGE_X_EJECTION = 8

# Volna
VOLNA_URON = 300
VOLNA_MINUS_MANA = 10
VOLNA_MINUS_V = 500
VOLNA_TIMER_FOR_S_2 = 15
VOLNA_TIMER_FOR_S = 180 + VOLNA_TIMER_FOR_S_2
VOLNA_TIMER_FOR_S_KD = 300
VOLNA_TIMER_FOR_S_OGLUSH = 90
VOLNA_TIMER_FOR_S_DVIZH = 3
VOLNA_DVIZH_FORCE_SPRITE = (75000, 9000)
VOLNA_CHANGE_X = 20
VOLNA_DVIZH_VEL_SPRITE = 1800


# BigVolna
BIG_VOLNA_URON = 600
BIG_VOLNA_MINUS_MANA = 20
BIG_VOLNA_MINUS_V = 1500
BIG_VOLNA_TIMER_FOR_S_2 = 45
BIG_VOLNA_TIMER_FOR_S = 120 + BIG_VOLNA_TIMER_FOR_S_2
BIG_VOLNA_TIMER_FOR_S_KD = 600
BIG_VOLNA_TIMER_FOR_S_OGLUSH = BIG_VOLNA_TIMER_FOR_S + 45
BIG_VOLNA_TIMER_FOR_S_DVIZH = BIG_VOLNA_TIMER_FOR_S - BIG_VOLNA_TIMER_FOR_S_2
BIG_VOLNA_DVIZH_FORCE_SPRITE = (150000, 0)
BIG_VOLNA_CHANGE_X = 10
BIG_VOLNA_DVIZH_VEL_SPRITE = BIG_VOLNA_CHANGE_X * 90


# RechnoyDrakon
RD_URON = 500
RD_MIN_URON = 40
RD_MINUS_MANA = 10
RD_MINUS_V = 12
RD_TIMER_FOR_S_ZADERZH = 30
RD_TIMER_FOR_S = 150 + RD_TIMER_FOR_S_ZADERZH
RD_TIMER_FOR_S_KD = 330
RD_DVIZH_FORCE_SPRITE = (60000, 0)
RD_DVIZH_VEL_SPRITE = 600
RD_FORCE_FOR_BLOCK = 1000000
RD_MINUS_FOR_BLOCK = 10
RD_SCALE = 1.5
RD_MAX_WIDHT = 900
RD_VR_WIDHT = 10000


# UdarKita
UK_URON = 1500
UK_MINUS_MANA = 40
UK_MINUS_V = 3500
UK_TIMER_FOR_S_ZADERZH = 60
UK_TIMER_FOR_S = 18 + UK_TIMER_FOR_S_ZADERZH
UK_TIMER_FOR_S_KD = 330
UK_TIMER_FOR_S_OGLUSH = 300
UK_TIMER_FOR_S_DVIZH_SPRITE = 10
UK_DVIZH_FORCE_SPRITE = (0, -20000)
UK_DVIZH_VEL_SPRITE = 10
UK_SCALE = 5


# Tayfun
TAYF_URON = 400
TAYF_MINUS_MANA = 10
TAYF_MINUS_V = 2000
TAYF_TIMER_FOR_S = 45
TAYF_TIMER_FOR_S_KD = 150
TAYF_TIMER_FOR_S_OGLUSH = 120
TAYF_TIMER_FOR_S_DVIZH_SPRITE = 75
TAYF_DVIZH_FORCE_SPRITE = (50000, 50000)
TAYF_DVIZH_VEL_SPRITE = 700
TAYF_DVIZH_FORCE_PERS = (0, 65000)


# Hlist
HLIST_URON = 125
HLIST_MINUS_MANA = 3
HLIST_MINUS_V = 60
HLIST_TIMER_FOR_S_ZADERZH = 7
HLIST_TIMER_FOR_S = 20 + HLIST_TIMER_FOR_S_ZADERZH
HLIST_TIMER_FOR_S_KD = 30
HLIST_TIMER_FOR_S_OGLUSH = 120
HLIST_TIMER_FOR_S_DVIZH_SPTITE = 60
HLIST_DVIZH_FORCE_SPRITE = (10000, -10000)
HLIST_DVIZH_VEL_SPRITE = 350
HLIST_SCALE = 2


# Lezviya
LEZVIYA_URON = 200
LEZVIYA_MINUS_MANA = 10
LEZVIYA_TIMER_FOR_S = 90
LEZVIYA_TIMER_FOR_S_KD = 300
LEZVIYA_TIMER_FOR_S_OGLUSH = 30
LEZVIYA_TIMER_FOR_S_DVIZH = 30
LEZVIYA_DVIZH_FORCE = (30000, 0)
LEZVIYA_DVIZH_VEL = 400

# Prityag



# Dop_sposobs


# VodaFightUdar
VFU_URON = 25
VFU_MINUS_MANA = 2
VFU_MINUS_V = 6
VFU_TIMER_FOR_S = 300
VFU_TIMER_FOR_S_KD = 60
VFU_TIMER_FOR_S_OGLUSH = 5
VFU_TIMER_FOR_S_DVIZH_SPRITE = 5
VFU_DVIZH_FORCE_SPRITE = (3000, 1000)
VFU_DVIZH_VEL_SPRITE = 100
VFU_CHANGE = 20
VFU_MINUS_CHANGE_X = 0.1
VFU_MINUS_CHANGE_Y = 1


# VodaFightUdars
VFUs_MINUS_V = 10
VFUs_TIMER_FOR_S_KD = 15
VFUs_KOL_VO = 12


# Karakatica
KARA_URON = 50
KARA_BAFF_URON = 3
KARA_KOMBO_BAFF_URON = 6
KARA_MINUS_MANA = 2
KARA_MINUS_V = 0
KARA_KOL_VO_UDARS = 4
KARA_TIMER_FOR_S = 15
KARA_TIMER_FOR_S_KD = 15
KARA_TIMER_FOR_S_OGLUSH = 35
KARA_TIMER_FOR_S_DVIZH_SPRITE = 30
KARA_DVIZH_VEL_SPRITE = 150
KARA_DVIZH_FORCE_SPRITE = (6000, 0)


# Techenie
TECH_URON = 5
TECH_MINUS_MANA = 1/60
TECH_MINUS_V = 0
TECH_TIMER_FOR_S_OGLUSH = 90
TECH_TIMER_FOR_S_DVIZH_SPRITE = 30
TECH_DVIZH_FORCE_SPRITE = (50000, -1000)
TECH_OTNOS = 115
TECH_SCALE = 1.75


# Reka
REKA_URON = 10
REKA_MINUS_MANA = 4/60
REKA_MINUS_V = 150
REKA_TIMER_FOR_S_OGLUSH = 150
REKA_TIMER_FOR_S_DVIZH_SPRITE = 60
REKA_DVIZH_FORCE_SPRITE = (50000, -50000)
REKA_OTNOS = 0


# VodaShchit
VSH_MINUS_MANA = 5
VSH_MINUS_V = 500
